image: alpine:3.14

stages:
  - build
  - release

build docker:
  image: tmaier/docker-compose:latest
  stage: build
  when: manual
  variables:
    IMAGE_TAG: qp3:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  script:
    - IMAGE_SAFE_TAG=$(echo $IMAGE_TAG | sed s#/#-#g)
    - pip install awscli
    - aws configure set aws_access_key_id $AMI_AWS_ACCESS_KEY
    - aws configure set aws_secret_access_key $AMI_AWS_SECRET_KEY
    - aws configure set region eu-central-1
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${AMI_OWNER}.dkr.ecr.eu-central-1.amazonaws.com
    - cd ./infrastructure
    - docker build --no-cache -f=Dockerfile --tag=$IMAGE_SAFE_TAG
        --build-arg S3_AWS_ACCESS_KEY=${S3_AWS_ACCESS_KEY}
        --build-arg S3_AWS_SECRET_KEY=${S3_AWS_SECRET_KEY}
        --build-arg SH_INSTANCE_ID=${SH_INSTANCE_ID}
        --build-arg SH_CLIENT_ID=${SH_CLIENT_ID}
        --build-arg SH_CLIENT_SECRET=${SH_CLIENT_SECRET}
        --build-arg SENTINELHUB_BRANCH=${SENTINELHUB_BRANCH}
        --build-arg EOLEARN_BRANCH=${EOLEARN_BRANCH}
        --build-arg LCMS_BRANCH=${LCMS_BRANCH}
        --build-arg HIECTOR_BRANCH=${CI_COMMIT_REF_NAME}
        .
    - docker tag ${IMAGE_SAFE_TAG} ${AMI_OWNER}.dkr.ecr.eu-central-1.amazonaws.com/${IMAGE_SAFE_TAG}
    - docker push ${AMI_OWNER}.dkr.ecr.eu-central-1.amazonaws.com/${IMAGE_SAFE_TAG}
    - echo ${IMAGE_SAFE_TAG}


release to github:
  stage: release
  when: always
  only:
    refs:
      - tags
  before_script:
    - apk add --no-cache git openssh-client
  script:
    - mkdir -m 700 ~/.ssh
    - echo "${GITHUB_SSH_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
    - git config user.email "eoresearch@sinergise.com"
    - git config user.name "Gitlab CI"
    - git remote rm github || true
    - git remote add github git@github.com:sentinel-hub/hiector.git
    - git branch -D github-upload || true
    - git checkout -b github-upload
    - git fetch origin release-changes
    - git merge origin/release-changes
    - git fetch github main
    - git reset --soft github/main
    - git commit -m "version $CI_COMMIT_TAG"
    - git push github github-upload:main
    - git push github HEAD:refs/tags/$CI_COMMIT_TAG
